spring:
  redis:
    host: 172.21.1.134
    port: 35001
    password: admin@redis
    database: 0
    timeout: 30000ms
    lettuce:
      pool:
        max-active: 10
        min-idle: 3
        max-idle: 10
  #        max-wait: -1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://172.21.1.134:1433;DatabaseName=nh_wms
      username: sa
      password: B@ojia56127
      max-active: 20
      initial-size: 2
      max-wait: 60000

notice:
  other-sys-addr:
    pallet-hand-in: http://172.21.1.135:8082/wcs/inboundAwait
    pallet-hand-out: http://172.21.1.135:8082/wcs/inboundAwait
    pallet-in: http://localhost:9090/wcs/taskReport
    pallet-out: http://172.21.1.135:8083/wms/nuohua/httpService/outboundTask
    pallet-error-in: http://localhost:9090/wcs/expose/pallet/error/in
    pallet-remove: http://localhost:9090/wcs/expose/pallet/remove
    stereoscopic-in: http://192.168.0.1:port/wcs/???
#LED看板硬件信息
led:
  #ip: 192.168.0.101
  ip: 172.32.2.28
  port: 5005

