spring:
  banner:
    location: banner.txt
    charset: UTF-8
  application:
    name: wcs
  redis:
    host: localhost
    port: 35001
    password: admin@redis
    database: 0
    timeout: 30000ms
    lettuce:
      pool:
        max-active: 10
        min-idle: 3
        max-idle: 10
  #        max-wait: -1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bj_wcs?characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      max-active: 20
      initial-size: 2
      max-wait: 60000
  profiles:
    active: dev

server:
  port: 9090
  servlet:
    context-path: /wcs
  tomcat:
    max-http-post-size: -1

# netty端口
netty:
  port: 50000


logging:
  config: classpath:logback-spring.xml
  path: E:\logs
  level:
    root: info
    web: info

mybatis:
  mapper-locations: classpath:mapping/wcs/*/*.xml,classpath*:mapping/*/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 框架工程自定义配置
framework:
  login-interceptor:
    exclude: /login,/framework/**,/wcsfront/**,/userManagement/login,/error,/expose/**,/view/**,/agv/**,/fourwaycar/**
#        - /login
#        - /framework/login.html
#        - /framework/css/**
#        - /framework/fonts/**
#        - /framework/images/**
#        - /framework/js/**
  authorization-interceptor:
    exclude: /login,/framework/**,/wcsfront/**,/userManagement/login,/error,/expose/**,/view/**,/agv/**,/fourwaycar/**
  #默认20分钟
  expiredTime: 20
  isOpenMail: 0
  #  上传文件大小限制,默认20M
  uploadFileSizeLimit: 20
  multipart:
    maxFileSize: 100MB

wcs:
  config:
#    是否开启tcp 客户端
    tcp-client: false
#    tcp-server-ip: 127.0.0.1
    tcp-server-ip: 192.168.0.11
    tcp-server-port: 2000
#    applyfactory: BAOBO
    ngx-path: http://localhost/
    #    X1  H1
    agv-task-typ: QXF1
    #    E m3
    agv-task-typ-pallet: QXF2
    #    X2 X3 H2 H3
    agv-task-typ-m67: QXF3

#    叠盘机码盘入库一拖的数量
    pallet-count-1003: 8
#默认DEFAULT
    applyfactory: DEFAULT

